[dbnode] Wide query iterator implementation
m3db/m3 pull request #2887
Opened 2020-11-12 21:55 UTC by arnikola

Provides an iterator over wide query results; resubmission off #2870

2020-11-13 11:37 UTC, linasm requested changes
My biggest concern - are we so desperate that we need to implement another memory manager?

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/types.go
> +	ShardIter(shard uint32) (QueryShardIterator, error)
This method name does not communicate enough about what it does. Guess adding some verb would help.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +const shardIterRecordsBuffer = 1024
```suggestion
const shardIterRecordsBufferSize = 1024
```

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +// nolint: hugeParam
Is this `nolint` needed?

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +	// returned for entire underlying buffer to be released.
When do we plan to implement this?

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +		opts:           opts,
`blockStart` is not being set.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +}
Wouldn't we want to close the `i.iters` channel?

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter.go
> +	reuseableID *ident.ReuseableBytesID
Typos:
```suggestion
	reusableID *ident.ReusableBytesID
```

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +	record   ShardIteratorRecord
Nit: maybe
```suggestion
	actual   ShardIteratorRecord
```

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/types.go
> +	Annotation  ts.Annotation
Also looks like these fields are not in any use.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +				vals:         append(make([]float64, 0, len(vals)), vals...),
Nit: don't think we need to take a copy here.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +		}
Nit: might just skip those Inc/DecRef in test code?
Probably needs `seg.Finalize()` if you want to get the full life cycle.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +		// opts         = NewOptions().SetDecodingOptions(decodingOpts)
Drop?

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +	record   ShardIteratorRecord
OTOH, `record` appears to be unused.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_prop_test.go
> +					if !assert.ObjectsAreEqual(shardVals[idx], record.expected.vals) {
It takes expected as the first argument.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_test.go
> +	assert.Equal(t, iter.SeriesMetadata(), SeriesMetadata{
Swap expected vs actual.

2020-11-13 11:37 UTC, linasm commented on src/dbnode/storage/wide/wide_query_iter_test.go
> +		EncodedTags: ts.EncodedTags([]byte("tags")),
Nit:
```suggestion
		ID:          []byte("id"),
		EncodedTags: []byte("tags"),
```

2020-11-17 18:32 UTC, arnikola commented on src/dbnode/storage/wide/fixed_buffer.go
> +			return nil, fixedBufferBorrowNoopGlobal, errTimeout
We want this to be strictly bounded more than anything; may add a strict mode that could toggle this behaviour

2021-01-18 09:28 UTC, closed without merging